import { BASEURL } from './globales'
export const listamenu = [
    {
      id: 59,
      texto: "Inicio",
      icono: "apps",
      color: "#a0aec0",
      url: `${BASEURL}/dashboard`,
      id_permiso:59,
    },
    {
      id: 44,
      texto: "Informes",
      icono: "trending_up",
      color: "#a0aec0",
      url: `${BASEURL}/informes`,
      id_permiso:44,
    },
    {
      id:62,
      texto: "Control",
      open:false,
      icono:"sports_esports",
      url:"url",
      id_permiso:62,
      submenu:[
        {
          id:69,
          texto:'Alumnos',
          icono:'group',
          color: "#a0aec0",
          url:`${BASEURL}/alumnos`,
          id_permiso:69
        },
        {
          id:63,
          texto:'Asistencias',
          icono:'fact_check',
          color: "#a0aec0",
          url:`${BASEURL}/asistencias`,
          id_permiso:63
        },
        {
          id:65,
          texto:'Abonos',
          icono:'paid',
          color: "#a0aec0",
          url:`${BASEURL}/abonos`,
          id_permiso:65
        },
        {
          id:67,
          texto:'Cuotas',
          icono:'account_balance_wallet',
          color: "#a0aec0",
          url:`${BASEURL}/cuotas`,
          id_permiso:67
        },
      ]
    },
    {
      id:58,
      texto: "Agendas",
      open:false,
      icono:"calendar_month",
      url:"url",
      id_permiso:58,
      submenu:[
        {
          id:49,
          texto:'Turnos',
          icono:'login',
          color: "#a0aec0",
          url:`${BASEURL}/turnos`,
          id_permiso:49
        },
        {
          id:51,
          texto:'Agenda',
          icono:'date_range',
          color: "#a0aec0",
          url:`${BASEURL}/agenda`,
          id_permiso:51
        },
      ]
    },
    {
      id: 53,
      texto: "Ventas",
      icono: "sell",
      color: "#a0aec0",
      url: "url",
      open: false,
      id_permiso:53,
      submenu: [
        {
          id: 1,
          texto: "Nueva venta",
          url: `${BASEURL}/ventas`,
          icono: "point_of_sale",
          color: "#a0aec0",
          id_permiso:1,
        },    
        {
          id: 6,
          texto: "Notas",
          url: `${BASEURL}/notas`,
          icono: "receipt",
          color: "#a0aec0",
          id_permiso:6,
        },
        {
          id: 4,
          texto: "Lista Facturas",
          url: `${BASEURL}/facturas`,
          icono: "assignment",
          color: "#a0aec0",
          id_permiso:4,
        },
        {
          id: 16,
          texto: "Entregas",
          url: `${BASEURL}/entregas`,
          icono: "delivery_dining",
          color: "#a0aec0",
          id_permiso:16,
        },
      ],
    },
    {
      id: 54,
      texto: "Productos",
      icono: "inventory_2",
      color: "#a0aec0",
      open: false,
      id_permiso:54,
      submenu: [
        {
          id: 91,
          texto: "Agregar",
          icono: "diamond",
          color: "#a0aec0",
          url: `${BASEURL}/productos/new`,
          id_permiso:9,
        },
        {
          id: 8,
          texto: "Lista de productos",
          icono: "content_paste",
          color: "#a0aec0",
          url: `${BASEURL}/productos`,
          id_permiso:8,
        },

        {
          id: 10,
          texto: "Categorías",
          icono: "category",
          color: "#a0aec0",
          url: `${BASEURL}/categorias`,
          id_permiso:10,
        },
        {
          id: 14,
          texto: "Proveedores",
          url: `${BASEURL}/proveedores`,
          icono: "local_shipping",
          color: "#a0aec0",
          id_permiso:14,
        },
        {
          id: 12,
          texto: "Marcas",
          url: `${BASEURL}/marcas`,
          icono: "branding_watermark",
          color: "#a0aec0",
          id_permiso:12,
        },
        {
          id: 18,
          texto: "Apartados",
          icono: "save",
          color: "#a0aec0",
          url: `${BASEURL}/apartados`,
          id_permiso:18,
        },
        
        {
          id:39,
          texto:"Depositos",
          url:`${BASEURL}/depositos`,
          icono:"local_convenience_store",
          color:"#a0aec0",
          id_permiso:39,
        },
        {
          id:60,
          texto:"Transferencias",
          url:`${BASEURL}/transferencias`,
          icono:"sync_alt",
          color:"#a0aec0",
          id_permiso:60,
        },
        {
          id: 43,
          texto: "Inventario",
          icono: "handyman",
          color: "#a0aec0",
          url: `${BASEURL}/inventario`,
          id_permiso:43,
        },
      ],
    },
    
    {
      id: 20,
      texto: "Compras",
      icono: "shopping_basket",
      color: "#a0aec0",
      url: `${BASEURL}/compras`,
      id_permiso:20,
    },
    {
      id: 55,
      texto: "Arqueos",
      icono: "savings",
      color: "#a0aec0",
      open: false,
      id_permiso:55,
      submenu: [
        {
          id: 22,
          texto: "Cajas",
          url: `${BASEURL}/cajas`,
          icono: `point_of_sale`,
          color: "#a0aec0",
          id_permiso:22,
        },
        {
          id: 24,
          texto: "Mov. de cajas",
          url: `${BASEURL}/movimientos`,
          icono: `leaderboard`,
          color: "#a0aec0",
          id_permiso:24,
        },
        {
          id: 26,
          texto: "Registro de mov.",
          url: `${BASEURL}/registromovimientos`,
          icono: `app_registration`,
          color: "#a0aec0",
          id_permiso:26,
        },
      ],
    },{
      id: 47,
      texto: "Cuentas",
      icono: "payments",
      color: "#a0aec0",
      url: `${BASEURL}/cuentas`,
      id_permiso:47,
      
    },
    {
      id: 56,
      texto: "Mantenimiento",
      icono: "engineering",
      color: "#a0aec0",
      open: false,
      id_permiso:56,
      submenu: [
        {
          id: 28,
          texto: "Clientes",
          url: `${BASEURL}/clientes`,
          icono: "people",
          color: "#a0aec0",
          id_permiso:28,
        },
        {
          id: 41,
          texto: "Empleados",
          url: `${BASEURL}/empleados`,
          icono: "badge",
          color: "#a0aec0",
          id_permiso:41,
        },
  
        {
          id: 30,
          texto: "Monedas",
          url: `${BASEURL}/monedas`,
          icono: "monetization_on",
          color: "#a0aec0",
          id_permiso:30,
        },
        {
          id: 32,
          texto: "Unidad de medida",
          icono: "square_foot",
          color: "#a0aec0",
          url: `${BASEURL}/medidas`,
          id_permiso:32,
        },
        {
          id: 45,
          texto: "Impuestos",
          icono: "account_balance",
          color: "#a0aec0",
          url: `${BASEURL}/impuestos`,
          id_permiso:45,
        },
        {
          id: 34,
          texto: "Usuarios",
          icono: "manage_accounts",
          color: "#a0aec0",
          url: `${BASEURL}/usuarios`,
          id_permiso:34,
        },
      ],
    },
  
    {
      id: 57,
      texto: "Ajustes",
      icono: "settings",
      color: "#a0aec0",
      id_permiso:57,
      open: false,
      submenu: [
        {
          id: 36,
          texto: "Datos de Empresa",
          icono: "admin_panel_settings",
          color: "#a0aec0",
          url: `${BASEURL}/settings`,
          id_permiso:36,
        },
        {
          id: 38,
          texto: "Registro de facturas",
          icono: "app_registration",
          color: "#a0aec0",
          url: `${BASEURL}/registrofacturas`,
          id_permiso:38,
        },
        {
          id: 59,
          texto: "Info y ayuda",
          icono: "help",
          color: "#a0aec0",
          url: `${BASEURL}/info`,
          id_permiso:59,
        },
      ],
    },
    
  ];
  