export const translates = {

    "en": 
        {
            "Inicio" : "Home",
            "Ventas": "Sales",
            "Realizar Ventas": "Make sales",
            "Informes": "Reports",
            "Ajustes": "Settings",
            "Productos":"Products",
            "Compras": "Purchase",
            "Cuentas": "Collection",
            "Nueva venta": "New sale",
            "Lista Facturas": "Sale list",
            "Lista facturas": "Sale list",
            "Arqueo de Cajas": "Cash registers",
            "Categorías":"Categories",
            "Categoría":"Category",
            "Artículos": "Articles",
            "Opciones" : "Options",
            "Código":"Code",
            "Bienvenido": "Welcome",
            "Mantenimiento":"Maintenance",
            "Entregas":"Deliveries",
            "Nombre":"Name",
            "Datos de Empresa":"Enterprise data",
            "Registro de facturas": "Bills register",
            "Clientes":"Customers",
            "Monedas":"Coins",
            "Impuestos":"Taxes",
            "Usuarios":"Users",
            "Unidad de medida": "Unit of measuremen",
            "Empleados":"Employees",
            "Mov. de cajas": "Movements",
            "Apertura/Cierre" : "Open/Close",
            "Cajas":"Registers",
            "Proveedores":"Providers",
            "Marcas":"Brands",
            "Apartados":"Transfers",
            "Inventario":"Inventory",
            "Depositos":"Deposits",
            "Lista de productos":"Products list",
            "Presupuestos":"Budget",
            "Realizar venta": "New sale",
            "Cotización": "Quotation",
            "SubModDashboard":"Welcome! This is the main panel of the system, here you can find shortcuts to access the different lists of each module of the system.",
            "Nuevo producto": "New product",
        }
    ,
    "es": 
        {
            "Inicio" : "Inicio",
            "Ventas": "Ventas",
            "Realizar Ventas": "Realizar ventas",
            "Informes": "Informes",
            "Ajustes": "Ajustes",
            "Productos":"Productos",
            "Compras": "Compras",
            "Cuentas": "Cuentas",
            "Nueva venta": "Nueva venta",
            "Lista Facturas": "Lista Facturas",
            "Arqueo de Cajas": "Arqueo de Cajas",
            "Categorías":"Categorías",
            "Categoría":"Categoría",
            "Artículos": "Artículos",
            "Opciones" : "Opciones",
            "Código":"Código",
            "Bienvenido": "Bienvenido",
            "Mantenimiento":"Mantenimiento",
            "Entregas":"Entregas",
            "Nombre":"Nombre",
            "Datos de Empresa":"Datos de Empresa",
            "Registro de facturas": "Registro de facturas",
            "Clientes":"Clientes",
            "Monedas":"Monedas",
            "Impuestos":"Impuestos",
            "Usuarios":"Usuarios",
            "SubModDashboard" :"¡Bienvenido! Este es el panel principal del sistema acá podrá encontrar atajos para acceder a los distintos listados de cada módulo del sistema.",
            "Nuevo producto": "Nuevo producto / servicio",
        }
    ,
    "pt": 
    {
        "Inicio" : "Inicio",
        "Ventas": "Vendas",
        "Realizar Ventas": "Realizar ventas",
        "Informes": "Informes",
        "Ajustes": "Ajustes",
        "Productos":"Productos",
        "Compras": "Compras",
        "Cuentas": "Cuentas",
        "Nuevo producto": "Novo produto",
    }
    

}